services:
  db:
    image: bitnami/postgresql:latest
    container_name: lantify_db
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=lantify
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
      - lantify

volumes:
  postgresql_data:

networks:
  lantify:
