services:
  db:
    image: bitnami/postgresql:latest
    container_name: lantify_db
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=lantify
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
      - lantify
  redis:
    image: bitnami/redis:latest
    container_name: lantify_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"
    networks:
      - lantify

volumes:
  postgresql_data:
  redis_data:

networks:
  lantify:
